Verify button
foundersandcoders/OTP-Data-Entry pull request #114
Opened 2018-03-20 21:24 UTC by Karyum

close #113 

the reason this PR is a bit big is becasue i had to change both events and places verify and found bit of bugs on the way

2018-03-27 10:48 UTC, des-des commented
@Karyum Everything is `verify.js` is in global scope

2018-03-27 10:56 UTC, des-des requested changes

2018-03-27 10:56 UTC, des-des commented on public/verify.js
> +var verifyButton = document.getElementById('verify-button');
This is in global scope !! ?? :cry:

2018-03-27 10:56 UTC, des-des commented on public/verify.js
> +var id = window.location.pathname.split('/')[3];
`id` is a very bad name (especially for something in global scope)

2018-03-27 10:56 UTC, des-des commented on public/verify.js
> +var url = 'http://localhost:3000/api/v1/' + resourceType;
? Localhost?

2018-03-27 10:56 UTC, des-des commented on public/verify.js
> +      var verifiedResource = Object.assign({}, res.data, {
Browser comparability?

2018-03-28 10:51 UTC, Karyum commented
yeah sorted it out :sweat_smile: :man_facepalming:

2018-04-08 10:41 UTC, des-des approved these changes

2018-04-08 10:42 UTC, merged