Initial server setup
foundersandcoders/OTP-Data-Entry pull request #20
Opened 2017-08-09 10:34 UTC by RQ16

#9

2017-08-09 13:27 UTC, m4v15 requested changes

2017-08-09 13:27 UTC, m4v15 commented on src/routes/home.js
> +module.exports = (req, res) => {
From what I've seen, more standard express layout is to call these controllers, not routes - https://www.terlici.com/2014/08/25/best-practices-express-structure.html

2017-08-09 13:27 UTC, m4v15 commented on src/routes/home.js
> +module.exports = (req, res) => {
so the router.js file is a router which you telling it what to do on the route but the this home.js file isn't a route necessarily it's a controller(or handler, but controller seems to be the term used in express) which your router.js calls on a route ('/')

2017-08-09 13:27 UTC, m4v15 commented on src/routes/router.js
> +router.get('/', require('./home.js'))
I think this is fine for the home route but for future routes possibly:

```js
router.route('places')
      .get(controllerhere)
      .post(contollerher)
```

Looks a lot better/is standard

2017-08-09 13:28 UTC, m4v15 commented
Sorry just a minor change to the folder name and potentially future route structure, otherwise it looks 👌  🥂

2017-08-09 13:30 UTC, m4v15 commented on src/routes/home.js
> +module.exports = (req, res) => {
let me know if that didn't make sense it's a bit of a ramble

2017-08-09 14:40 UTC, m4v15 commented
assigning you @des-des as well as I think you said at one point you might want to look over the first few PRs and this one is small

2017-08-11 12:43 UTC, des-des approved these changes

2017-08-11 12:43 UTC, des-des commented on src/routes/home.js
> +module.exports = (req, res) => {
:+1:

2017-08-14 10:36 UTC, m4v15 requested changes

2017-08-14 10:36 UTC, m4v15 commented on tests/test.js
> +      t.error(err);
At the moment this test gives the text `null` which isn't super helpful, could just add a message like:

` t.error(err, 'Error test');`

Also I guess this is just a initial set up, but you're not really testing anything here, just that you don't get an error. 

Could have a check to test the right response is sent back - check that the `res.text` includes something from your template?

2017-08-15 10:02 UTC, RQ16 commented on tests/test.js
> +      t.error(err);
Since it is an initial setup so I thought there was no need to

2017-08-15 10:51 UTC, m4v15 commented on tests/test.js
> +      t.error(err);
Yeah I mean it's not a huge deal either way, I just wasn't sure

2017-08-15 10:53 UTC, m4v15 approved these changes

2017-08-15 10:54 UTC, merged