Get all places [WIP]
foundersandcoders/OTP-Data-Entry pull request #24
Opened 2017-08-21 10:17 UTC by RQ16

#10

2017-08-21 12:34 UTC, m4v15 commented
So just couple of things before you move on:

 - This is just for the `/en/` end point at the moment - the `/ar/` is going to be exactly the same but at [these lines](https://github.com/foundersandcoders/OTP-Data-Entry/pull/24/files#diff-9fd324f26492298896db69d1b1b4ab3R8) just change it to `this.ar.whatever`

- Regarding that, instead of [having text written directly in handlebars](https://github.com/foundersandcoders/OTP-Data-Entry/pull/24/files#diff-89fd324f26492298896db69d1b1b4ab3R1), we should have a javascript file which holds a languages object with both english and arabic, that we require in at the top of the server, then we can use it in handlebars. A bit like the way we did it in easyNaz:
   - [text file](https://github.com/FACN1/easyNaz/blob/master/text.js)
   - [using it](https://github.com/FACN1/easyNaz/blob/master/app.js#L17-L25)

2017-08-21 12:38 UTC, m4v15 commented on src/controllers/router.js
> +router.get('/en/places', require('./places.js').getAll);
I don't really like this layout it looks a bit confusing - think it'd be better to require ./places at the top as `placesController` or something and then do `placesController.getAll` here

2017-08-21 12:43 UTC, m4v15 commented
Sorry, I should really be reviewing this before you assign me, just a few things I thought of ☝️ 

It all looks 👌  apart from the stuff I mentioned

2017-08-21 12:44 UTC, JWLD commented
Cheers @m4v15 , when you linked to 'these lines' it links to the general PR for me - which lines did you mean?

2017-08-21 12:50 UTC, m4v15 commented
@JWLD sorry habibi I meant here https://github.com/foundersandcoders/OTP-Data-Entry/blob/f390363f3df118f7420c7dce9e0411a386af15ae/views/places.hbs#L1

2017-08-21 12:51 UTC, m4v15 commented
Oooo wow I've never seen it do that in comment rendering before

2017-08-21 15:47 UTC, m4v15 commented on src/app.js
> +app.locals.text = languages['english'];
we're not always going to want this to be english.

Could do:

```
app.locals.textEn = languages['english']
app.locals.textAr = languages['arabic']
```

Actually, why not `languages.english`?

2017-08-22 07:43 UTC, m4v15 commented on src/controllers/places.js
> +    const data = JSON.parse(body);
I think we need to filter the data here to make sure we only have results that contain `en.name` fields (they don't all have to)

2017-08-22 07:49 UTC, m4v15 commented on views/places.hbs
> +        <span class="place-wrap__span">{{en.description}}</span>
So anything that's not `required` in the API schema [here](https://github.com/foundersandcoders/open-tourism-platform/blob/master/docs.md#create-place) we need to check whether or not it exists in the response

2017-08-22 07:50 UTC, m4v15 commented on views/places.hbs
> +        <span class="place-wrap__span">{{en.description}}</span>
Otherwise we might get back a load of undefined/empty responses

2017-08-22 07:51 UTC, m4v15 commented on src/controllers/places.js
> +    const data = JSON.parse(body);
using `array.filter`

2017-08-25 22:12 UTC, m4v15 commented
So is this done?

2017-08-25 23:44 UTC, RQ16 commented
Yes, @m4v15

2017-08-25 23:46 UTC, RQ16 commented
Functionality wise, but no styling

2017-08-26 09:02 UTC, m4v15 commented
Cool, take off the WIP tag and write a message so i know to review and merge or request changes. @RQ16

2017-08-27 14:03 UTC, m4v15 requested changes
What happened to the `dir` stuff? Did you decide against it? Apart from that this looks good.

2017-08-31 14:14 UTC, m4v15 commented
@RQ16 if we finish this before we get started on any others that would be 👌 .

So in the placesController we should find out what language we are in (using `req.params.lang`) and then have a switch statement to set a const called `dir` as either `ltr` or `rtl` (left-to-right, etc)

We can then pass this as data into the view, and in the html tag in the layouts/main.hbs, here:
https://github.com/foundersandcoders/OTP-Data-Entry/blob/2b2389d687604bd03ed9c8567c4b3a151fbbe0b1/views/layouts/main.hbs#L2

You can add a text direction attribute, like [here](https://github.com/FACN1/easyNaz/blob/master/views/layouts/main.hbs)

2017-09-02 17:13 UTC, RQ16 commented
@m4v15 Is adding the lang variable as an attribute essential here? Is the dir one not sufficient?

2017-09-03 06:19 UTC, m4v15 commented
If we have access to it, we might has well, looks like it might be useful

https://www.w3.org/International/questions/qa-lang-why

(These are the language codes)[http://www.iana.org/assignments/language-subtag-registry/language-subtag-registry] 

So it looks like 'en' and 'ar' will work

So our controller will look something like this

```js
// Some if statement to work out and set a dir variable

res.render('places', {
       output: data,
       localLang: req.app.locals[req.params.lang].
       lang: req.params.lang
       dir
     });
```

2017-09-05 07:15 UTC, m4v15 commented
🎉 😍

2017-09-05 07:15 UTC, m4v15 approved these changes

2017-09-05 07:17 UTC, merged