Get specific place [WIP]
foundersandcoders/OTP-Data-Entry pull request #26
Opened 2017-08-25 14:38 UTC by RQ16

#13 
Get specific place information

2017-09-05 07:26 UTC, m4v15 commented
You've assigned me to review but it's still a WIP, right?

We need to do the language and text direction for this stuff as wel

2017-09-05 07:28 UTC, m4v15 commented on views/place.hbs
> +  <li>Name:
don't use Name - use `localLang.name` or like in views/places

2017-09-05 13:54 UTC, RQ16 commented
@m4v15 I have added the text direction and language stuff- It is ready for reviewing.

2017-09-05 14:58 UTC, m4v15 requested changes

2017-09-05 14:58 UTC, m4v15 commented on views/place.hbs
> +    <a href="{{place.imageUrl}}">View</a>
Why are these links and not images?

2017-09-05 14:58 UTC, m4v15 commented on views/place.hbs
> +    <a href="{{place.website}}">View</a>
Yeah I'd maybe change these to images

2017-09-05 15:00 UTC, m4v15 commented
I don't think we have to rush to get this through before this sprint planning tbh

2017-09-05 15:06 UTC, m4v15 commented on views/place.hbs
> +    {{place.location}}
This could be a map?

2017-09-12 10:05 UTC, Suuuuha commented
@m4v15 changes have been made!

2017-09-12 11:41 UTC, m4v15 approved these changes

2017-09-12 11:50 UTC, m4v15 commented
looking good 🔥

2017-09-12 11:51 UTC, merged