Oauth {WIP}
foundersandcoders/OTP-Data-Entry pull request #68
Opened 2017-10-16 14:06 UTC by Suuuuha

related #62

2017-10-18 09:47 UTC, m4v15 requested changes

2017-10-18 09:47 UTC, m4v15 commented on src/middleware/checkLoggedIn.js
> +  const token = req.cookies.token;
change to `const token = req.cookies && req.cookies.token `

2017-10-18 09:47 UTC, m4v15 commented on src/controllers/router.js
> +router.get('/:lang/loginOauth', oauthCode);
can we change this route just `/:lang/login` - this looks a bit messy

2017-10-19 06:56 UTC, JWLD commented
Think you might've forgotten to push `package.json` btw!

2017-10-19 07:32 UTC, m4v15 requested changes

2017-10-19 07:32 UTC, m4v15 commented on src/controllers/OAuth/token.js
> +      if (error || res.statusCode !== 200) {
should be `response.statusCode`

2017-10-19 07:32 UTC, m4v15 commented on src/controllers/OAuth/token.js
> +      if (error || res.statusCode !== 200) {
Maybe change the `response` variable in the `Request` part to `tokenResponse` or something to avoid confusion

2017-10-19 07:32 UTC, m4v15 commented on src/controllers/OAuth/token.js
> +      errorMessage: res.locals.localText.oauthError
I don't think this error message will work, will need to use plain english like down there👇

2017-10-19 10:28 UTC, m4v15 commented on src/helpers/check_cookie.js
> +  if (req.cookies.token) {
sorry should have seen this before: change to `(req.cookies && req.cookies.token)`

2017-10-19 10:31 UTC, m4v15 requested changes

2017-10-19 10:31 UTC, m4v15 commented on src/controllers/places/delete_place.js
> +  if (req.cookies.token) {
and again... 
>😬  sorry I should have seen this before: change to `(req.cookies && req.cookies.token)` to avoid any errors

2017-10-19 10:31 UTC, m4v15 commented on src/helpers/check_cookie.js
> +  if (req.cookies.token) {
once more... 
>😬  sorry I should have seen this before: change to `(req.cookies && req.cookies.token)` to avoid any errors

2017-10-19 10:31 UTC, m4v15 commented on src/controllers/events/delete_event.js
> +  if (req.cookies.token) {
😬  sorry I should have seen this before: change to `(req.cookies && req.cookies.token)` to avoid any errors

2017-10-19 10:56 UTC, m4v15 approved these changes

2017-10-19 10:57 UTC, m4v15 commented
@JWLD happy for you to merge when you're ready

2017-10-19 12:01 UTC, merged